set_path;
save_git_hash;

%Add dependent executables for tsne and phenograph
%tsne
tsne_files = [...
        "histoCAT/3rdParty/bh_tsne/bh_tsne_mac64",...
        "histoCAT/3rdParty/bh_tsne/bh_tsne_win64.exe",...
        "histoCAT/3rdParty/bh_tsne/bh_tsne_win32.exe",...
        "histoCAT/3rdParty/bh_tsne/bh_tsne_linux64",...
        "histoCAT/3rdParty/bh_tsne/bh_tsne_linux32",...
        ];
%phenograph
phenograph_files = get_phenograph_files();

fprintf('Start compiling\n');
buildResults = compiler.build.standaloneApplication('histoCAT.m', ...
    'OutputDir','compilation_output',...
    'ExecutableIcon', 'histoCAT.png',...
    'ExecutableSplashScreen', 'histoCAT.png',...
    'AdditionalFiles',[tsne_files, phenograph_files]);
fprintf('Start creating installer\n');
installer_opts = compiler.package.InstallerOptions(...
    buildResults,'OutputDir','installer_output',...
    'Version', get_histoCAT_version,...
    'InstallerName','histoCAT_Installer',...
    'ApplicationName','histoCAT',...
    'InstallerSplash', 'histoCAT.png',...
    'InstallerIcon', 'histoCAT.png',...
    'InstallerLogo', 'histoCAT.png'...
    );
compiler.package.installer(buildResults,'Options',installer_opts)
fprintf('DONE\n');