addpath(genpath(pwd))
save_git_hash;
fprintf('Start compiling\n');
buildResults = compiler.build.standaloneApplication('histoCAT.m', ...
    'OutputDir','../compilation_output',...
    'ExecutableIcon', 'histoCAT.png',...
    'ExecutableSplashScreen', 'histoCAT.png'...
    );
fprintf('Start creating installer\n');
installer_opts = compiler.package.InstallerOptions(...
    buildResults,'OutputDir','../installer_output',...
    'Version', get_histoCAT_version,...
    'InstallerName','histoCAT_Installer',...
    'ApplicationName','histoCAT',...
    'InstallerSplash', 'histoCAT.png',...
    'InstallerIcon', 'histoCAT.png',...
    'InstallerLogo', 'histoCAT.png'...
    );
compiler.package.installer(buildResults,'Options',installer_opts)
fprintf('DONE\n');