addpath(genpath(pwd))
buildResults = compiler.build.standaloneApplication("histoCAT.m", ...
    'OutputDir','compilation_output');
installer_opts = compiler.package.InstallerOptions(...
    buildResults,'OutputDir','installer_output',...
    'Version', get_histoCAT_version,...
    'InstallerName',"histoCAT_Installer",...
    'ApplicationName',"histoCAT"...
    );
compiler.package.installer(buildResults,'Options',installer_opts)