function [rgb_Image] = make_rgb(mask,colorstouse,loopnum)
% MAKE_RGB: Sets the RGBCMY color for each selected channel(tiff) of the
% current sample.
%
% Input:
% mask --> input mask to be colored
% colorstouse --> colormap generated by jet for the number of
% selected channels
% loopnum --> count of loop through the selected gates
%
% Histology Topography Cytometry Analysis Toolbox (histoCAT)
% Denis Schapiro - Bodenmiller Group - UZH


%Create an RGB image from the mask 
forothercolors = cat(3,double(mask),double(mask),double(mask));

%Store it in another variable
currentcells_color = forothercolors;

%Assign the third dimension RGB based on each row of the jet colors
currentcells_color(:,:,1) = colorstouse(loopnum,1);
currentcells_color(:,:,2) = colorstouse(loopnum,2);
currentcells_color(:,:,3) = colorstouse(loopnum,3);

%Store this RGB image 
rgb_Image = currentcells_color;

end

