name: MATLAB Build

on:
  #push:
  #  branches: [ main, master ]
  #pull_request:
  #  branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

env:
  MLM_LICENSE_TOKEN: ${{ secrets.matlab_token }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest, 
          #windows-latest, 
          #macos-latest
          ]
    
    steps:
      
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      
    - name: Run MATLAB Command
      uses: matlab-actions/run-command@v2
      with:
        command: addpath(genpath('.')); disp('MATLAB environment initialized');
        
    - name: Run MATLAB Compiler
      uses: matlab-actions/run-command@v2
      with:
        command: compile
        
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: histoCAT-compiled
        path: |
          ../compilation_output
